### ISSUE TITLE
Refactor 17 lines occurring 3 times in TilesetCanvas.cpp

### ISSUE THREAD

**Issue by Rover656** [NerdThings/Ngine#16]
I've selected for refactoring 17 lines of code which are duplicated in 1 file(s) ([1](https://github.com/NerdThings/Ngine/blob/0896d8a875e64f01b83868133c211fee658713cf/src/Graphics/TilesetCanvas.cpp#L39-L61), [2](https://github.com/NerdThings/Ngine/blob/0896d8a875e64f01b83868133c211fee658713cf/src/Graphics/TilesetCanvas.cpp#L116-L138), [3](https://github.com/NerdThings/Ngine/blob/0896d8a875e64f01b83868133c211fee658713cf/src/Graphics/TilesetCanvas.cpp#L78-L100)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by UltimaBGD** [comment]
Are you still looking for assistance on this? If so, I can take a look at it. 

In addition, do you have any specific requests on how to handle the for loops?

**Comment by Rover656** [comment]
Hi there, first of all, thanks for your interest.
Feel free to have a go at any of these issues. All of these methods could probably be rewritten as one single method that does everything. If you have any better ideas, feel free to create a PR! :smile:

**Comment by UltimaBGD** [comment]
We can extract the duplicated code and the for loops to one method that each of the 3 other methods would call with a flag telling the merged function what for loop to run. The for loop statements would still technically be duplicated in that instance, but it may be better to have those lines repeated than have a check in the for loops for what code to run.

**Comment by UltimaBGD** [comment]
The validation code alone could easily be extracted to a smaller function, but that leaves the creation of the shape vector duplicated across each, as well as the creation of sX sY eX eY as pointers to pass in for validation. This would be a small scale fix that still fixes the duplication of 10 lines each time.

**Comment by Rover656** [comment]
Closing this as the class was removed for rewriting in the develop branch.
